### ISSUE TITLE
The demo doesn't seem to work

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#16]

**Comment by maxkfranz** [comment]
I used this link from the readme: https://rawgit.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/master/demo.html

**Comment by maxkfranz** [comment]
I don't see anything after I click an edge.  I tried on Chrome and Safari

**Comment by kinimesi** [comment]
@maxkfranz Please read the readme:
- in order to add a bend point, first you need to select that edge, then right click where you want to add the bend point and click `Add Bend Point` on the context menu
- Alternatively, you can click anywhere on the selected edge to introduce and relocate a bend point by dragging

See the GIF below (created in Safari):
![teeamdjqq0](https://user-images.githubusercontent.com/7281872/42004698-a736ab34-7a79-11e8-9f2b-c94b2b39e327.gif)

**Comment by maxkfranz** [comment]
You're right.  I missed that.  I must have been thinking of a previous version of the demo or a different demo that presented things differently.

It might be good to simplify the demo with a pre-existing bend point shown -- if possible.
